#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ -e "${ZDOTDIR:-$HOME}/.zshenv.secret" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshenv.secret"
fi

export PATH="$PATH:/Users/pfista/.foundry/bin"
. "$HOME/.cargo/env"
