if [ -f ~/.dotfiles/bash/bashrc ]; then
   source ~/.dotfiles/bash/bashrc
fi
export EDITOR=vim
export TERM=xterm-256color
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"
export PATH="$PATH:/usr/local/Cellar/eb/macosx/python2.7"

if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi
