if [ -f ~/.dotfiles/bash/bashrc ]; then
   source ~/.dotfiles/bash/bashrc
fi
export EDITOR=vim
export TERM=xterm-256color
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"
export PATH="$PATH:/usr/local/Cellar/eb/macosx/python2.7"


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

#####  RMN Environment stuff ######
export PATH=$PATH:/usr/local/mysql/bin/
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/

export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=128m"

if type virtualenvwrapper.sh >/dev/null 2>&1; then
    source "$(which virtualenvwrapper.sh)"
elif [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    source /usr/local/bin/virtualenvwrapper.sh
elif [ -f /usr/local/share/python/virtualenvwrapper.sh ]; then
    source /usr/local/share/python/virtualenvwrapper.sh
fi

if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi

# JAVA_HOME=$(/usr/libexec/java_home)
JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home"

alias vsqlprod="/opt/vertica/bin/vsql -U dbadmin"

# IFFTS
alias push-heroku='git subtree push --prefix=backend heroku master' 
