if [ -f ~/.dotfiles/bash/bashrc ]; then
   source ~/.dotfiles/bash/bashrc
fi
export EDITOR=vim
export TERM=xterm-256color
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
